version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: lets-build-a-forum-with-laravel/app
    ports:
     - "${APP_PORT}:80"
    volumes:
     - .:/var/www/html
    networks:
    - sdnet
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: lets-build-a-forum-with-laravel/node
    volumes:
     - .:/var/www/html
    networks:
     - sdnet
  mysql:
    image: mysql:5.7
    ports:
     - "${DB_PORT}:3306"
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - sdnet
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
  redis:
    image: redis:alpine
    networks:
     - sdnet
networks:
  sdnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
